[package]
name = "stake"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.17.0"
thiserror = "1.0.50"
spl-token = "4.0.0"
spl-associated-token-account = "2.2.0"
borsh = "0.10.3"
borsh-derive = "0.10.3"

[lib]
crate-type = ["cdylib", "lib"]
